# Generated by Django 6.1 on 2026-07-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.CharField(max_length=100),
        ),
    ]
